name: Validate Helm Chart

on:
  push:
    branches:
      - main

jobs:
  validate-chart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: validate
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E 'https://.+?_Linux_x86_64.tar.gz')" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan
          sudo install terrascan /usr/local/bin
          cd terraform/
          terrascan scan -i helm